### PR TITLE
SFS-4514: Change depth frame name

### PR DESCRIPTION
**Pull request by hendryjoe**
Change the depth frame name to the new version.

### CODE REVIEW

**Review by rsinnet — COMMENTED** [review]
Does this work in sim?

**Comment by hendryjoe** [comment]
> Does this work in sim?

this is for actual realsense and not used in sim

**Comment by rsinnet** [comment]
> > Does this work in sim?
> 
> this is for actual realsense and not used in sim

Hmm I thought the new realsense sim driver might use this?

**Review by rsinnet — COMMENTED** [review]
Does this match kinetic?

**Comment by hendryjoe** [comment]
This only changes the topic name, so it only matches kinetic if we also change the topic name on the kinetic

**Review by zzv2 — APPROVED** [review]

**Pull request merged**
