### PR TITLE
release/10.0.4

### PR DESCRIPTION
**Pull request by Schwo0ps**

### CODE REVIEW

**Comment by jrwhite1987** [comment]
What's the deal with Shippable? The last several commits haven't built but I didn't think we had Shippable for this repo....

**Comment by Schwo0ps** [comment]
@jrwhite1987 It's failing because there is no shippable file, so not sure what's up with that.
@rsinnet, can we disable shippable for this repo?
image

**Comment by jrwhite1987** [comment]
Status?

**Comment by Schwo0ps** [comment]
I think the Shippable has always been like that. It's not required to merge though, so just gonna merge it. It looks like it's running really well at Walmart :tada:

**Pull request merged**
