### PR TITLE
Remove log message in gray to color conversion

### PR DESCRIPTION
**Pull request by zzv2**
This log really gives us no information and is filling the logs
making it difficult to find more important information.

### CODE REVIEW

**Review by Schwo0ps — APPROVED** [review]
Sweet. You can change to `logdebug` if you think the information is ever gonna be useful for debugging this node.

**Review by ludwig — APPROVED** [review]

**Comment by zzv2** [comment]
@Schwo0ps I don't think it would ever really be useful, only the errors.

**Comment by rsinnet** [comment]
It seems like this PR name is misleading.

**Comment by zzv2** [comment]
@rsinnet how so? I removed the log message

**Pull request merged**
